<?php
/**
 * @file
 * Code for the Newsletter bundle.
 */

/**
 * Implements hook_secure_permissions().
 */
function cu_newsletter_bundle_secure_permissions($role) {
   $permissions = array(
    'administrator' => array(
      'create newsletter content',
      'delete any newsletter content',
      'delete own newsletter content',
      'edit any newsletter content',
      'edit own newsletter content',
      'create any newsletter_list bean',
      'delete any newsletter_list bean',
      'edit any newsletter_list bean',
      'view any newsletter_list bean',
    ),
    'content_editor' => array(
      'create newsletter content',
      'delete any newsletter content',
      'delete own newsletter content',
      'edit any newsletter content',
      'edit own newsletter content',
      'create any newsletter_list bean',
      'delete any newsletter_list bean',
      'edit any newsletter_list bean',
      'view any newsletter_list bean',
    ),
    'developer' => array(
      'create newsletter content',
      'delete any newsletter content',
      'delete own newsletter content',
      'edit any newsletter content',
      'edit own newsletter content',
      'create any newsletter_list bean',
      'delete any newsletter_list bean',
      'edit any newsletter_list bean',
      'view any newsletter_list bean',
    ),
    'site_owner' => array(
      'create newsletter content',
      'delete any newsletter content',
      'delete own newsletter content',
      'edit any newsletter content',
      'edit own newsletter content',
      'create any newsletter_list bean',
      'delete any newsletter_list bean',
      'edit any newsletter_list bean',
      'view any newsletter_list bean',
    ),
    'anonymous user' => array(
      'view any newsletter_list bean',
    ),
    'authenticated user' => array(
      'view any newsletter_list bean',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_express_node_list_groups().
 * Provided by express_add_content.api.php.
 */
function cu_newsletter_bundle_express_node_list_groups($bundles) {

  $bundles['news']['types'][] = 'Newsletter';

  return $bundles;
}

/**
 * Implements hook_express_bean_list_groups().
 * Provided by express_add_content.api.php.
 */
function cu_newsletter_bundle_express_bean_list_groups($bundles) {

  $bundles['news']['types'][] = 'Newsletter List';

  return $bundles;
}
