<?php

/**
 * @file
 * cu_logout_users.module
 */

/**
 * Implements hook_form_user_login_alter().
 */
function cu_logout_users_form_user_login_alter(&$form, &$form_state) {

 if (!array_key_exists('fit_7179', $_GET)) {
  $form['name']['#disabled'] = 'disabled';
  $form['pass']['#disabled'] = 'disabled';
  unset($form['#validate']);
  unset($form['#submit']);
  unset($form['actions']);

  $link = l('follow this link', 'http://www.colorado.edu/webcentral/node/704');
  drupal_set_message(t('Logging into your CU website has been temporarily disabled for an update. It will be re-enabled shortly. For issues related to this update, please <a href="@link">follow this link</a>.', array('@link' => 'http://www.colorado.edu/webcentral/node/704')), 'warning', FALSE);
 }
}