<?php

/**
 * @file
 * Contains hooks for cu_local_users module.
 */

/**
 * Implements hook_form_alter().
 *
 * Mirrors changes cu_ldap makes without the overhead of LDAP.
 */
function cu_local_users_form_user_login_alter(&$form, &$form_state) {
  $form['name']['#title'] = t('CU Login Name');
  $form['name']['#description'] = '';
  $form['pass']['#title'] = t('IdentiKey Password');
  $form['pass']['#description'] = '';
}
