<?php

/**
 * @file
 * Install hooks for ng_hosting module.
 */

/**
 * Implements hook_install().
 */
function ng_hosting_install() {
  variable_set('session_cookie_lifetime_type', 'time');
  variable_set('session_cookie_lifetime_multiplier', 3600);
  variable_set('session_cookie_lifetime_amount', 26);
}


/**
 * Express 2.8.4 Update. Add session_cookie_lifetime requirement.
 */
function ng_hosting_update_7001() {
  // NO LONGER ENABLE SESSION COOKIE LIFETIME
}
