<?php

/**
 * @file
 * Defines roles and permissions for the Express profile.
 * Also used to alter some existing core and contrib permissions.
 */

/**
 * Implements hook_permission().
 *
 * Add 'add taxonomy' permission.
 */
function express_permissions_permission() {
  $permissions = array(
    'create vocabulary' => array(
      'title' => t('Create Vocabulary'),
      'description' => 'Used to override default Taxonomy permissions.  Users with Administer Taxonomy cannot add new vocabularies without this additional permission.',
    ),
  );
  return $permissions;
}

/**
 * Implements hook_menu_alter.
 * Alters permissions on some core and contrib menus
 */
function express_permissions_menu_alter(&$items) {
  // Prevent users from adding taxonomies.
  $items['admin/structure/taxonomy/add']['access arguments'] = array('create vocabulary');
}

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function express_permissions_secure_permissions_roles() {
  return array(
    'anonymous user',
    'authenticated user',
    'edit_my_content',
    'edit_only',
    'site_editor',
    'site_owner',
    'administrator',
    'developer',
    'content_editor',
    'content_editor',
    'access_manager',
    'configuration_manager',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function express_permissions_secure_permissions($role) {
  $permissions = array(
    'administrator' => array(
      'access administration pages',
      'access bean overview',
      'access ckeditor link',
      'access content',
      'access content overview',
      'access contextual links',
      'access express settings',
      'access user profiles',
      'access users overview',
      'access_google_appliance_content',
      'administer beans',
      'administer blocks',
      'administer checked out documents',
      'administer contexts',
      'administer express settings',
      'administer express theme picker',
      'administer menu',
      'administer nodes',
      'administer people settings',
      'administer redirects',
      'assign content_editor role',
      'assign edit_my_content role',
      'assign site_owner role',
      'cancel users with role authenticated user',
      'cancel users with role content_editor',
      'cancel users with role edit_my_content',
      'cancel users with role site_owner',
      'check out documents',
      'clear full caches',
      'clear path caches',
      'create any block bean',
      'create any feature_callout bean',
      'create any hero_unit bean',
      'create any slider bean',
      'create faqs content',
      'create file content',
      'create page content',
      'create url aliases',
      'customize shortcut links',
      'delete any block bean',
      'delete any faqs content',
      'delete any file content',
      'delete any hero_unit bean',
      'delete any page content',
      'delete any slider bean',
      'delete own faqs content',
      'delete own file content',
      'delete own page content',
      'delete revisions',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit cu blocks',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'edit users with role authenticated user',
      'edit users with role content_editor',
      'edit users with role edit_my_content',
      'edit users with role site_owner',
      'execute node_assign_owner_action',
      'execute node_make_sticky_action',
      'execute node_make_unsticky_action',
      'execute node_promote_action',
      'execute node_publish_action',
      'execute node_unpromote_action',
      'execute node_unpublish_action',
      'execute node_unpublish_by_keyword_action',
      'execute views_bulk_operations_delete_item',
      'invite new user',
      'preview focal point',
      'revert revisions',
      'use bigmenu',
      'use text format wysiwyg',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view express environment indicator',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'enable module bundles',
      'view status messages',
      'view warning messages',
      'view error messages', // currently only the perms below diff with site owner role
      'administer cache settings',
      'configure profile module manager',
      'view unused beans',
      'diff view changes',
    ),
    'anonymous user' => array(
      'access content',
      'access_google_appliance_content',
      'view any block bean',
      'view any feature_callout bean',
      'view any hero_unit bean',
      'view any quicktab bean',
      'view any slider bean',
      'view status messages',
      'view warning messages',
      'view error messages',
    ),
    'authenticated user' => array(
      'access content',
      'access_google_appliance_content',
      'delete own webform submissions',
      'skip CAPTCHA',
      'view any block bean',
      'view any feature_callout bean',
      'view any hero_unit bean',
      'view any quicktab bean',
      'view any slider bean',
      'view status messages',
      'view warning messages',
      'view error messages',
    ),
    'content_editor' => array(
      'access administration pages',
      'access bean overview',
      'access ckeditor link',
      'access content overview',
      'access contextual links',
      'access express reports',
      'access express settings',
      'access user profiles',
      'administer beans',
      'administer contexts',
      'administer menu',
      'administer nodes',
      'check out documents',
      'clear path caches',
      'create any block bean',
      'create any feature_callout bean',
      'create any hero_unit bean',
      'create any slider bean',
      'create faqs content',
      'create file content',
      'create page content',
      'create url aliases',
      'customize shortcut links',
      'delete any block bean',
      'delete any faqs content',
      'delete any file content',
      'delete any hero_unit bean',
      'delete any page content',
      'delete any slider bean',
      'delete own faqs content',
      'delete own file content',
      'delete own page content',
      'delete revisions',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit cu blocks',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'execute node_assign_owner_action',
      'execute node_make_sticky_action',
      'execute node_make_unsticky_action',
      'execute node_promote_action',
      'execute node_publish_action',
      'execute node_unpromote_action',
      'execute node_unpublish_action',
      'execute node_unpublish_by_keyword_action',
      'execute views_bulk_operations_delete_item',
      'preview focal point',
      'revert revisions',
      'use bigmenu',
      'use text format wysiwyg',
      'view any hero_unit bean',
      'view any slider bean',
      'view bean page',
      'view bean revisions',
      'view any unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'view status messages',
      'view warning messages',
      'view error messages',
      'diff view changes',
    ),
    'developer' => array(
      'access administration pages',
      'access all views',
      'access bean overview',
      'access ckeditor link',
      'access configuration administration',
      'access content',
      'access content overview',
      'access contextual links',
      'access cu version information',
      'access environment indicator',
      'access express settings',
      'access site in maintenance mode',
      'access site reports',
      'access user profiles',
      'access users overview',
      'access_google_appliance_content',
      'administer actions',
      'administer bean settings',
      'administer bean types',
      'administer beans',
      'administer bigmenu',
      'administer blocks',
      'administer boxes',
      'administer CAPTCHA settings',
      'administer checked out documents',
      'administer ckeditor link',
      'administer content types',
      'administer contexts',
      'administer rave alerts',
      'administer express settings',
      'administer express theme picker',
      'administer features',
      'administer fields',
      'administer field collections',
      'administer fieldgroups',
      'administer filters',
      'administer fitvids',
      'administer flexslider',
      'administer google analytics',
      'administer honeypot',
      'administer image styles',
      'administer menu',
      'administer meta tags',
      'administer modernizr',
      'administer module filter',
      'administer module missing message fixer',
      'administer modules',
      'administer nodes',
      'administer people settings',
      'administer pathauto',
      'administer permissions',
      'administer recaptcha',
      'administer redirect settings',
      'administer redirects',
      'administer shortcuts',
      'administer site configuration',
      'administer software updates',
      'administer string overrides',
      'administer system menus',
      'administer taxonomy',
      'administer themes',
      'administer url aliases',
      'administer users',
      'administer video styles',
      'administer views',
      'administer_google_appliance',
      'admin_display_suite',
      'assign administrator role',
      'assign all roles',
      'assign content_editor role',
      'assign developer role',
      'assign edit_my_content role',
      'assign site_owner role',
      'block IP addresses',
      'bypass follow form validation',
      'cancel account',
      'change administration theme',
      'change own username',
      'check out documents',
      'clear full caches',
      'clear path caches',
      'context ajax block access',
      'create any block bean',
      'create any feature_callout bean',
      'create any hero_unit bean',
      'create any slider bean',
      'create faqs content',
      'create file content',
      'create page content',
      'create person content',
      'create url aliases',
      'create vocabulary',
      'customize shortcut links',
      'delete any block bean',
      'delete any faqs content',
      'delete any file content',
      'delete any hero_unit bean',
      'delete any page content',
      'delete any slider bean',
      'delete own faqs content',
      'delete own file content',
      'delete own page content',
      'delete revisions',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit bean view mode',
      'edit boxes',
      'edit cu blocks',
      'edit locked contexts',
      'edit meta tags',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'execute node_assign_owner_action',
      'execute node_make_sticky_action',
      'execute node_make_unsticky_action',
      'execute node_promote_action',
      'execute node_publish_action',
      'execute node_unpromote_action',
      'execute node_unpublish_action',
      'execute node_unpublish_by_keyword_action',
      'execute views_bulk_operations_delete_item',
      'export secure permissions',
      'generate features',
      'invite new user',
      'manage features',
      'notify of path changes',
      'opt-in or out of tracking',
      'preview focal point',
      'revert revisions',
      'select account cancellation method',
      'switch shortcut sets',
      'use bigmenu',
      'use PHP for tracking visibility',
      'use text format full_html',
      'use text format wysiwyg',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view express environment indicator',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'enable module bundles',
      'enable admin bundles',
      'view status messages',
      'view warning messages',
      'view error messages',
      'exclude from message filtering',
      'configure profile module manager',
      'administer cache settings',
      'administer elysia_cron',
      'execute elysia_cron',
      'view elysia_cron',
      'view unused beans',
      'diff view changes',
    ),
    'edit_my_content' => array(
      'access ckeditor link',
      'access content overview',
      'access_google_appliance_content',
      'administer nodes',
      'check out documents',
      'edit own page content',
      'edit own person content',
      'preview focal point',
      'skip CAPTCHA',
      'use text format wysiwyg',
      'view any block bean',
      'view any feature_callout bean',
      'view any hero_unit bean',
      'view any quicktab bean',
      'view any slider bean',
      'view the administration theme',
      'access navbar',
      'view status messages',
      'view warning messages',
      'view error messages',
      'diff view changes',
    ),
    'site_editor' => array(
      'access administration pages',
      'access bean overview',
      'access ckeditor link',
      'access content',
      'access content overview',
      'access contextual links',
      'access express settings',
      'access user profiles',
      'access users overview',
      'administer beans',
      'administer blocks',
      'administer checked out documents',
      'administer contexts',
      // 'administer express settings',
      'administer menu',
      'administer nodes',
      'administer redirects',
      'clear path caches',
      'check out documents',
      'create any block bean',
      'create any feature_callout bean',
      'create any hero_unit bean',
      'create any slider bean',
      'create faqs content',
      'create file content',
      'create page content',
      'create url aliases',
      'customize shortcut links',
      'delete any block bean',
      'delete any faqs content',
      'delete any file content',
      'delete any hero_unit bean',
      'delete any page content',
      'delete any slider bean',
      'delete own faqs content',
      'delete own file content',
      'delete own page content',
      'delete revisions',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit cu blocks',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'execute node_assign_owner_action',
      'execute node_make_sticky_action',
      'execute node_make_unsticky_action',
      'execute node_promote_action',
      'execute node_publish_action',
      'execute node_unpromote_action',
      'execute node_unpublish_action',
      'execute node_unpublish_by_keyword_action',
      'execute views_bulk_operations_delete_item',
      'preview focal point',
      'revert revisions',
      'use bigmenu',
      'use text format wysiwyg',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'view status messages',
      'view warning messages',
      'view error messages',
      'diff view changes',
    ),
    'site_owner' => array(
      'access administration pages',
      'access bean overview',
      'access ckeditor link',
      'access content',
      'access content overview',
      'access contextual links',
      'access express reports',
      'access express settings',
      'access user profiles',
      'access users overview',
      'administer beans',
      'administer blocks',
      'administer checked out documents',
      'administer contexts',
      'administer express settings',
      'administer express theme picker',
      'administer menu',
      'administer nodes',
      'administer people settings',
      'administer redirects',
      'assign content_editor role',
      'assign edit_my_content role',
      'assign site_owner role',
      'cancel users with role authenticated user',
      'cancel users with role content_editor',
      'cancel users with role edit_my_content',
      'cancel users with role site_owner',
      'check out documents',
      'clear full caches',
      'clear path caches',
      'create any block bean',
      'create any feature_callout bean',
      'create any hero_unit bean',
      'create any slider bean',
      'create faqs content',
      'create file content',
      'create page content',
      'create url aliases',
      'customize shortcut links',
      'delete any block bean',
      'delete any faqs content',
      'delete any file content',
      'delete any hero_unit bean',
      'delete any page content',
      'delete any slider bean',
      'delete own faqs content',
      'delete own file content',
      'delete own page content',
      'delete revisions',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit cu blocks',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'edit users with role authenticated user',
      'edit users with role content_editor',
      'edit users with role edit_my_content',
      'edit users with role site_owner',
      'execute node_assign_owner_action',
      'execute node_make_sticky_action',
      'execute node_make_unsticky_action',
      'execute node_promote_action',
      'execute node_publish_action',
      'execute node_unpromote_action',
      'execute node_unpublish_action',
      'execute node_unpublish_by_keyword_action',
      'execute views_bulk_operations_delete_item',
      'invite new user',
      'preview focal point',
      'revert revisions',
      'use bigmenu',
      'use text format wysiwyg',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'enable module bundles',
      'view status messages',
      'view warning messages',
      'view error messages',
      'diff view changes',
    ),
    'edit_only' => array(
      'access administration pages',
      'access bean overview',
      'access ckeditor link',
      'access content overview',
      'access contextual links',
      'access express settings',
      'access navbar',
      'administer nodes', // this is needed to access content overview page
      'check out documents',
      'clear path caches',
      'create url aliases',
      'customize shortcut links',
      'diff view changes',
      'edit any block bean',
      'edit any faqs content',
      'edit any file content',
      'edit any hero_unit bean',
      'edit any page content',
      'edit any slider bean',
      'edit own faqs content',
      'edit own file content',
      'edit own page content',
      'preview focal point',
      'revert revisions',
      'use text format wysiwyg',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view error messages',
      'view revisions',
      'view status messages',
      'view the administration theme',
      'view warning messages',
    ),
    'access_manager' => array(
      'access administration pages',
      // 'access express settings',
      'access user profiles',
      'access users overview',
      'assign content_editor role',
      'assign edit_my_content role',
      'assign site_owner role',
      'cancel users with role authenticated user',
      'cancel users with role content_editor',
      'cancel users with role edit_my_content',
      'cancel users with role site_owner',
      'edit users with role authenticated user',
      'edit users with role content_editor',
      'edit users with role edit_my_content',
      'edit users with role site_owner',
      'invite new user',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'view status messages',
      'view warning messages',
      'view error messages',
    ),
    'configuration_manager' => array(
      'access administration pages',
      'access bean overview',
      'access content',
      'access content overview',
      'access express settings',
      'access user profiles',
      'access users overview',
      'administer redirects',
      'administer express settings',
      'administer express theme picker',
      'administer site search',
      'clear full caches',
      'clear path caches',
      'create url aliases',
      'revert revisions',
      'use bigmenu',
      'view any block bean',
      'view any hero_unit bean',
      'view any slider bean',
      'view any unpublished content',
      'view bean page',
      'view bean revisions',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
      'access navbar',
      'enable module bundles',
      'view status messages',
      'view warning messages',
      'view error messages',
      'diff view changes',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add validation to user form.
 */
function express_permissions_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  $form['#validate'][] = 'express_permissions_site_owner_cap';

  $new_role_options = array();
  // Get Roles of user being edited.
  $original_role_options = $form['account']['roles']['#options'];

  foreach ($original_role_options as $rid => $role_name) {
    // Format role name to be  more readable.
    $new_role_name = check_plain($role_name);
    $new_role_name = ucwords(str_replace('_', ' ', $new_role_name));
    if ($role_name == 'edit_only') {
      if (in_array('developer', $user->roles) || in_array('administrator', $user->roles)) {
        $new_role_name =  '<i>' . $new_role_name . ' (temp role hidden from site owners)</i>';
      }
    }
    if ($role_name == 'access_manager') {
      if (in_array('developer', $user->roles) || in_array('administrator', $user->roles)) {
        $new_role_name =  '<i>' . $new_role_name . ' (hidden from site owners until 2.9.1)</i>';
      }
    }
    if ($role_name == 'configuration_manager') {
      if (in_array('developer', $user->roles) || in_array('administrator', $user->roles)) {
        $new_role_name =  '<i>' . $new_role_name . ' (hidden from site owners until 2.9.1)</i>';
      }
    }
    $new_role_options[$rid] = $new_role_name;

  }

  $form['account']['roles']['#options'] = $new_role_options;
}

/**
 * Validation function for user form.
 *
 * Check to make sure that there are no more than 5 site owners.
 */
function express_permissions_site_owner_cap(&$form, &$form_state) {
  // Limit of how many of the role we should allow.
  $limit = intval(variable_get('express_permissions_owner_cap', 5));

  // Get Roles of user being edited.
  $current_roles = $form_state['user']->roles;

  // Get Role ID.
  $role = user_role_load_by_name('site_owner');

  // Check to see if the user already has the role.
  // We should only run the validation of the role is being added.
  if (in_array($role->rid, $form_state['values']['roles'], TRUE) && !isset($current_roles[$role->rid])) {
    $users_in_role = express_permissions_get_site_owners();
    // If adding the role to this user would be over the limit, set an error.
    if ($users_in_role['count'] > $limit) {

      form_set_error("roles][$rid", "You have exceeded the allowed limit for Temporary Site Owners. To grant the role to this user you must first remove it from someone else. Current Site Owners include: " . $users_in_role['list']);
    }
  }

}

function express_permissions_form_user_external_invite_form_alter(&$form, &$form_state) {
  $form['#validate'][] = 'express_permissions_invite_site_owner_cap';
}

function express_permissions_invite_site_owner_cap(&$form, &$form_state) {
  // Limit of how many of the role we should allow.
  $limit = intval(variable_get('express_permissions_owner_cap', 5));

  // Get Role ID.
  $role = user_role_load_by_name('site_owner');

  if ($form_state['values']['rid'] == $role->rid) {
    $email_value = $form_state['values']['email'];
    // Split on , or line break.
    $emails = preg_split("/[\r\n,\s]+/", $email_value, -1, PREG_SPLIT_NO_EMPTY);
    $email_count = count($emails);
    $users_in_role = express_permissions_get_site_owners();
    if (($users_in_role['count'] + $email_count > $limit)) {
      form_set_error("", "You have exceeded the allowed limit for Temporary Site Owners. To grant this role you must first remove it from someone else. Current Site Owners include: " .  $users_in_role['list']);
    }
  }

}

/**
 * Helper funciton for form validation.
 *
 * Returns arary with count and list values
 */
function express_permissions_get_site_owners() {
  $users = array();
// Get Role ID.
  $role = user_role_load_by_name('site_owner');
  $rid = $role->rid;

  // Get current number of people with the role.
  // Get the total number of users with the role.
  $query = db_select('users_roles', 'ur');
  $query->fields('ur', array('uid', 'rid'));
  $query->condition('ur.rid', $rid, '=');
  $users['count'] = $query->countQuery()->execute()->fetchField();

  // try to avoid loading user objects
  if ($users['count'] > 5) {
      $results = $query->execute()->fetchCol();
      $site_owners = user_load_multiple($results);
      $user_list = array();
      foreach ($site_owners as $site_owner) {
        $user_list[] = !empty($site_owner->realname) ? $site_owner->realname : $site_owner->mail;
      }
     $users['list'] = join(', ', $user_list);
  }
  return $users;
}

/**
 * Implements hook_form_formid_alter().
 *
 * Remove underscores from roles to make the permissions table display better.
 */
function express_permissions_form_user_admin_permissions_alter(&$form, &$form_state) {
  $roles = $form['role_names'];
  // Get just the role arrays.
  $roles = array_intersect_key($roles, array_flip(element_children($roles)));
  // Replace underscores with spaces.
  foreach ($roles as $id) {
    $name = str_replace('_', ' ', $form['role_names'][$id]['#markup']);
    $form['role_names'][$id]['#markup'] = $name;
  }
  // Add some css to make the permissions table headers smaller.
  drupal_add_css('form#user-admin-permissions #permissions th { font-size:75%; font-weight:bold; } form#user-admin-permissions #permissions .permission-machine-name { font-size:75%; opacity:.75;}', 'inline');
}
