<?php

/**
 * @file
 * Provides additional styles for quicktabs.
 */

/**
 * Implements hook_quicktabs_tabstyles().
 *
 * @return array
 *   An array of tabstyles.
 */
function cu_quicktab_styles_quicktabs_tabstyles() {
  $tabstyles_directory = drupal_get_path('module', 'cu_quicktab_styles') . '/tabstyles';
  $files = file_scan_directory($tabstyles_directory, '/\.css$/');
  $tabstyles = array();
  foreach ($files as $file) {
    // Skip RTL files.
    if (!strpos($file->name, '-rtl')) {
      //$tabstyles[$file->uri] = drupal_ucfirst($file->name);
    }
  }
  $tabstyles['line.css'] = 'Line';
  $tabstyles['circles.css'] = 'Circles';
  $tabstyles['dark.css'] = 'Dark';
  $tabstyles['minimal.css'] = 'Minimal';
  $tabstyles['simple.css'] = 'Simple';
  $tabstyles['tabs.css'] = 'Tabs';
  $tabstyles['triangles.css'] = 'Triangles';
  $tabstyles['vertical.css'] = 'Vertical';
  return $tabstyles;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 *   Quicktabs form array.
 * @param array $form_state
 *   Current values in quicktabs form.
 * @param string $form_id
 *   Form ID of the quicktabs form.
 */
function cu_quicktab_styles_form_quicktabs_form_alter(array &$form, array &$form_state, $form_id) {

  // When adding a quicktab, it will not initially have a machine name.
  $machine_name = isset($form['machine_name']['#value']) ? $form['machine_name']['#value'] : '';

  // The quicktab renderer should be returned with the form, but it is not.
  // Rather than fix in quicktab project, we are adding it here to avoid the module issue queue.
  $qt_renderer = db_query('SELECT renderer FROM {quicktabs} q WHERE q.machine_name = :name', array(':name' => $machine_name))->fetchField();

  unset($form['style']['#options']['Arrows']);
  unset($form['style']['#options']['Basic']);
  unset($form['style']['#options']['Bullets']);
  unset($form['style']['#options']['Excel']);
  unset($form['style']['#options']['Garland']);
  unset($form['style']['#options']['Mac']);
  unset($form['style']['#options']['Navlist']);
  unset($form['style']['#options']['Phylactere']);
  unset($form['style']['#options']['Sky']);
  unset($form['style']['#options']['Zen']);

  // It easier for end users to understand a "tabs" vs. "ui_tabs" option.
  $form['renderer']['#options']['ui_tabs'] = 'tabs';

  if ($qt_renderer != 'quicktabs') {
    unset($form['renderer']['#options']['quicktabs']);
  }
  else {
    drupal_set_message(t('The quicktabs rendering options has been deprecated. If you choose a different render option, you will not be able to switch back to the quicktabs render option.'), 'warning');
  }

  // Since there are several known issues with quicktabs and since we don't want
  // to keep changing code for these edge cases, provide a link to help article.
  $form['troubleshooting_link'] = array(
    '#type' => 'markup',
    '#markup' => '<p><strong>' . t('Note: ') . '</strong>' .
    t('There are several known issues with displaying quicktabs. If you are experiencing issues, please read: !help_link',
    array('!help_link' => '<a href="' . variable_get('express_help_base_url') . '/troubleshooting-quicktabs">Troubleshooting Quicktabs</a>')) . '</p>',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 *   Quicktabs form array.
 * @param array $form_state
 *   Current values in quicktabs form.
 * @param string $form_id
 *   Form ID of the quicktabs form.
 */
function cu_quicktab_styles_form_quicktabs_tabstyles_styles_alter(array &$form, array &$form_state, $form_id) {
  unset($form['quicktabs_tabstyle']['#options']['Arrows']);
  unset($form['quicktabs_tabstyle']['#options']['Basic']);
  unset($form['quicktabs_tabstyle']['#options']['Bullets']);
  unset($form['quicktabs_tabstyle']['#options']['Excel']);
  unset($form['quicktabs_tabstyle']['#options']['Garland']);
  unset($form['quicktabs_tabstyle']['#options']['Mac']);
  unset($form['quicktabs_tabstyle']['#options']['Navlist']);
  unset($form['quicktabs_tabstyle']['#options']['Phylactere']);
  unset($form['quicktabs_tabstyle']['#options']['Sky']);
  unset($form['quicktabs_tabstyle']['#options']['Zen']);
}

/**
 * Implements hook_page_alter().
 *
 * @param array $page
 *   The page array that will be rendered to the screen.
 */
function cu_quicktab_styles_page_alter(array &$page) {
  drupal_add_css(drupal_get_path('module', 'cu_quicktab_styles') . '/css/cu_quicktab_styles.css');
  drupal_add_js(drupal_get_path('module', 'cu_quicktab_styles') . '/js/cu_quicktab_styles.js', array(
    'type' => 'file',
    'scope' => 'footer',
    'weight' => 50
  ));
}
