<?php
/**
 * @file
 * Install hooks for the cu_users_tests module.
 */

/**
 * Implements hook_install().
 */
function cu_users_tests_install() {
  // Create user to assign content to and then delete.
  $role = user_role_load_by_name('site_editor');
  $new_user = array(
    'name' => 'temp_site_editor',
    'pass' => 'temp_site_editor',
    'mail' => 'noreply@nowhere.com',
    'status' => 1,
    'init' => 'noreply@nowhere.com',
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
      $role->rid => 'site_editor',
    ),
  );

  try {
    // The first parameter is sent blank so a new user is created.
    $temp_content_editor = user_save('', $new_user);
  } catch (Exception $exception) {
    watchdog('cu_users_test', $exception->getMessage());
  }

  // Set default user to local 'site_owner' test user.
  variable_set('cu_users_reassign_content_user', 'site_owner');

  // Create content.
  // Install text block beans.
  $beans[0] = array(
    'title' => 'Text Block A',
    'content' => 'Text Block A Content AAA',
    'delta' => 'block-a-1'
  );

  $beans[1] = array(
    'title' => 'Text Block B',
    'content' => 'Text Block B Content BBB',
    'delta' => 'block-b-2'
  );

  foreach ($beans as $key => $value) {
    $bean = bean_create(array('type' => 'block'));
    $bean->label = $value['title'];
    $bean->title = $value['title'];
    $bean->delta = $value['delta'];
    $bean->uid = $temp_content_editor->uid;
    $bean->field_block_text = array(
      LANGUAGE_NONE => array(array(
        'value' => $value['content'],
      )),
    );
    $bean->save();
  }
}
