<?php

/**
 * @file
 * Module that pings Drupal's servers for relaying usage statistics.
 */

/**
 * Implements hook_update_projects_alter().
 */
function cu_update_ping_update_projects_alter(&$projects) {

  // We want to run this mainly to report usage of our hosted modules on drupal.org.
  $modules_to_check = array(
    'et_slate_form',
    'embed_templates',
    'siteimprove_api',
    'atlas',
    'rave_alerts',
    'express_theme_picker',
    'express_help',
    'express_settings',
    'profile_version',
    'express',
    'context_bean_ui',
    'profile_module_manager',
    'community_funded',
    'webform_captcha',
    'user_external_invite',
    'block_title_icons',
    'backstretch',
    'dslm',
    'secure_permissions',
    'site_verify',
    'bundles',
    'noreqnewpass',
    'google_cse'
  );

  $modules_list = array();
  foreach ($projects as $key => $project) {
    if (in_array($key, $modules_to_check)) {
      $modules_list[$key] = $project;
    }
  }

  // Set $projects to only include our modules.
  $projects = $modules_list;
}
