<?php

/**
 * @file
 * Programmatically create VCR content. Oh Yeah!
 *
 * Will create pages, menus and menu items, beans and more.
 * More power!
 */


function get_redirect_final_target($url) {
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_NOBODY, 1);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1); // follow redirects
  curl_setopt($ch, CURLOPT_AUTOREFERER, 1); // set referer on redirect
  curl_exec($ch);
  $target = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
  curl_close($ch);
  if ($target)
    return $target;
  return false;
}
