<?php

/**
 * Implements hook_user_login().
 *
 * Send user to dashboard after logging in.
 */
function express_dashboard_user_user_login(&$edit, $account)
{
  // Your logic will set $redirection to the desired location
  $redirection = 'admin/dashboard/user';

  // Unless there is already a redirection going, or the user is trying to reset his password, we redirect to $redirection.
  if (empty($_GET['destination'])
    && !is_null($redirection)
    && (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset'))
  {
    $edit['redirect'] = $redirection;
  }
}

/**
 * Implements hook_express_dashboard().
 *
 * Adding user Dashboard.
 */
function express_dashboard_user_express_dashboard($variables) {
  $variables['user'] = array(
    'title' => 'User Dashboard',
    'callback' => 'express_dashboard_user_content',
    'weight' => -99,
    'access arguments' => array('use user dashboard'),
  );
  return $variables;
}

/**
 * Implements hook_permission().
 */
function express_dashboard_user_permission() {
  return array(
    'use user dashboard' => array(
      'title' => 'Use the User Dashboard',
      'description' => 'Access the user dashboard',
    ),
  );
}

/**
 * Callback function for user dashboard.
 */
function express_dashboard_user_content() {
  $output = array();
  $output['top']['widgets']['one']['title'] = 'Top Section One';
  $output['top']['widgets']['one']['content']['#markup'] = '<p>This is the user dashboard!!!</p>';
  $output['top']['weight'] = 1;

  $output['middle']['widgets']['one']['title'] = 'Middle Section One';
  $output['middle']['widgets']['one']['content']['#markup'] = '<p>This is the user dashboard section one.</p>';
  $output['middle']['widgets']['one']['weight'] = 100;



  $output['bottom']['widgets']['one']['title'] = 'Bottom Section Four';
  $output['bottom']['widgets']['one']['content']['#markup'] = '<p>This is the user dashboard bottom section.</p>';

  return $output;
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */

function express_dashboard_user_secure_permissions($role) {

  $permissions = array(
    'administrator' => array(
      'use user dashboard',
    ),
    'content_editor' => array(
      'use user dashboard',
    ),
    'developer' => array(
      'use user dashboard',
    ),
    'edit_my_content' => array(
      'use user dashboard',
    ),
    'site_owner' => array(
      'use user dashboard',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
