<?php
/**
 * @file
 * Code for the CU Linkchecker feature.
 */

include_once 'cu_linkchecker.features.inc';

/**
 * Implements hook_page_alter().
 */
function cu_linkchecker_page_alter(&$page) {
  if (current_path() == 'admin/reports/linkchecker' && variable_get('linkchecker_disable_cron_link_check', 0)) {
    drupal_set_message('Link checking has been temporarily disabled on your site. Links will not be checked again until an administrator turns back on the functionality.', 'warning');
  }
}

function cu_linkchecker_menu() {
  $items = array();
  $items['admin/settings/seo/linkchecker-analyze'] = array(
    'title' => 'Link Checker - Analyze Content',
    'description' => 'Scan your content for links. Run this if you have just enabled the SEO Bundle.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_linkchecker_analyze_form'),
    'access arguments' => array('access broken links report'),
    'weight' => 25,
  );
  return $items;
}

function cu_linkchecker_analyze_form() {
  $form = array();
  $form['description'] = array(
    '#markup' => '<p>The site content needs to be analyzed for links for the link checker to work. Once analyzed, the links will be queued to check for broken links. You should only analyze your content when the link checker is first enabled. After the content has been analyzed, all new links will automatically be added to the queue.</p>',
  );
  $form['clear']['linkchecker_analyze'] = array(
    '#type' => 'submit',
    '#value' => t('Analyze content for links'),
    '#submit' => array('cu_linkchecker_analyze_form_submit'),
  );
  return $form;
}

function cu_linkchecker_analyze_form_submit($form, $form_state) {
  module_load_include('inc', 'linkchecker', 'linkchecker.admin');
  linkchecker_analyze_links_submit();
  variable_set('cu_linkchecker_status', 1);
  drupal_set_message('The site\'s content has been analyzed for links and the links have been added to the link checker queue.');
}
