<?php

/**
 * @file
 * A dashboard for checking the status of SEO-related tools.
 */

/**
 * Implements hook_menu().
 */
function cu_seo_dashboard_express_dashboard($variables) {
  $variables = array();

  $variables['seo'] = array(
    'title' => 'SEO Dashboard',
    'callback' => 'cu_seo_dashboard_content',
    'access arguments' => array('view seo dashboard'),
  );

  return $variables;
}

/**
 * Implements hook_permission().
 */
function cu_seo_dashboard_permission() {
  return array(
    'view seo dashboard' => array(
      'title' => 'View SEO Dashboard',
      'description' => 'View the dashboard at admin/dashboard/seo',
    ),
    'administer seo dashboard' => array(
      'title' => 'Administer SEO Dashboard',
      'description' => 'Administer the dashboard at admin/dashboard/seo',
    ),
  );
}


/**
 * Callback for 'admin/dashboard/seo'.
 */
function cu_seo_dashboard_content() {
  $output = array();

  $output['top']['widgets']['one']['title'] = 'SEO Dashbaord';
  $output['top']['widgets']['one']['content']['#markup'] = 'you you';

  return $output;
}
