<?php

/**
 * Implements hook_block_info().
 */
function express_layout_master_pages_block_info() {
  return array(
    'el_block_header' => array(
      'info' => t('Node Header'),
      'cache' => DRUPAL_NO_CACHE,
      'weight' => -50,
    ),
    'el_block_footer' => array(
      'info' => t('Node Footer'),
      'cache' => DRUPAL_NO_CACHE,
      'weight' => 50,
    ),
    'el_block_sidebar_first' => array(
      'info' => t('Node Sidebar First'),
      'cache' => DRUPAL_NO_CACHE
    ),
    'el_block_sidebar_second' => array(
      'info' => t('Node Sidebar Second'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_inner_content_left' => array(
      'info' => t('Node Inner Content Left'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_inner_content_right' => array(
      'info' => t('Node Inner Content Right'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_intro' => array(
      'info' => t('Intro'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_slider' => array(
      'info' => t('Slider'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_wide_2' => array(
      'info' => t('Post Wide'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'el_block_inner_content_bottom' => array(
      'info' => t('Node Inner Content Bottom'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

function express_layout_master_pages_block_view($delta = '') {
  
}
