<?php
/**
 * @file
 * Code for the CU Linkchecker feature.
 */

include_once 'cu_linkchecker.features.inc';

/**
 * Implements hook_page_alter().
 *
 * @param $vars
 */
function cu_linkchecker_page_alter(&$vars) {
  if (current_path() == 'admin/reports/linkchecker') {
    $form = drupal_render(drupal_get_form('cu_linkchecker_reports_form'));
    $vars['content']['system_main']['cu_linkchecker_check'] = array(
      '#markup' => $form,
    );
  }
}

/**
 * Form for checking links on the linkchecker report page.
 *
 * @return array
 */
function cu_linkchecker_reports_form() {
  $form = array();

  $form['clear']['linkchecker_help_text'] = array();

  $form['clear']['linkchecker_clear_analyze'] = array(
    '#type' => 'submit',
    '#value' => t('Scan content for links'),
    '#submit' => array('cu_linkchecker_clear_analyze_links_submit'),
    '#attributes' => array(
      'class' => array(
        'btn btn-primary',
      ),
    ),
  );
  /*
  $form['clear']['linkchecker_check_links'] = array(
    '#type' => 'submit',
    '#value' => t('Check for broken links'),
    '#submit' => array('cu_linkchecker_check_links_submit'),
    '#attributes' => array(
      'class' => array(
        'btn btn-primary',
      ),
    ),
  );
  */
  if (REQUEST_TIME - variable_get('cu_linkchecker_analyze_links_last', 0) <= 86400) {
    $form['clear']['linkchecker_clear_analyze']['#suffix'] = '<p>Due to high load on the server, you can only scan content for links once every day.</p>';
    $form['clear']['linkchecker_clear_analyze']['#disabled'] = TRUE;
  }
  return $form;
}

/**
 * Submit callback.
 *
 * Clear link data and analyze fields in all content types, comments, custom
 * blocks.
 */
function cu_linkchecker_clear_analyze_links_submit($form, &$form_state) {
  // Set variable so people can't repeatedly press the button.
  variable_set('cu_linkchecker_analyze_links_last', REQUEST_TIME);

  // Check links on install.
  db_truncate('linkchecker_block_custom')->execute();
  db_truncate('linkchecker_comment')->execute();
  db_truncate('linkchecker_node')->execute();
  db_truncate('linkchecker_link')->execute();

  // Start batch and analyze all nodes.
  $node_types = array_keys(array_filter(variable_get('linkchecker_scan_nodetypes', array())));
  if (!empty($node_types)) {
    module_load_include('inc', 'linkchecker', 'linkchecker.batch');
    batch_set(_linkchecker_batch_import_nodes($node_types));
    if (variable_get('linkchecker_scan_comments', 0)) {
      batch_set(_linkchecker_batch_import_comments($node_types));
    }
  }
  if (variable_get('linkchecker_scan_blocks', 0)) {
    module_load_include('inc', 'linkchecker', 'linkchecker.batch');
    batch_set(_linkchecker_batch_import_block_custom());
  }
}

function cu_linkchecker_check_links_submit() {
  module_load_include('module', 'linkchecker', 'linkchecker');
  linkchecker_cron();
  variable_set('cu_linkchecker_cleanup_links_last', REQUEST_TIME);
}
