<?php

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
  
function cu_seo_bundle_secure_permissions($role) {
  // INSERT PERMISSIONS FOR THIS BUNDLE
  $permissions = array(
    'administrator' => array(
      'edit meta tags',
      'administer meta tags',
      'administer xmlsitemap',
    ),
    'anonymous user' => array(
    ),
    'authenticated user' => array(
    ),
    'content_editor' => array(
      'edit meta tags',
    ),
    'developer' => array(
      'edit meta tags',
      'administer meta tags',
      'administer xmlsitemap',
    ),
    'edit_my_content' => array(
    ),
    'site_owner' => array(
      'edit meta tags',
      'administer meta tags',
      'administer xmlsitemap',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_express_help().
 *
 * Add contextual help for the SEO Bundle.
 *
 * @param $variables
 *   Array with information about help hooks
 * @return $variables
 */
function cu_seo_bundle_express_help($variables) {
  $variables['admin/config/search/metatags'][] = array(
    'title' => 'Metatag Settings Help',
    'short_title' => 'Metatag Settings Help',
    'url' => 'http://www.colorado.edu/webcentral/node/724',
  );
  $variables['admin/config/search/metatags/settings'][] = array(
    'title' => 'Metatag Settings Help',
    'short_title' => 'Metatag Settings Help',
    'url' => 'http://www.colorado.edu/webcentral/node/724',
  );
  $variables['admin/config/search/metatags/bulk-revert'][] = array(
    'title' => 'Metatag Settings Help',
    'short_title' => 'Metatag Settings Help',
    'url' => 'http://www.colorado.edu/webcentral/node/724',
  );

  return $variables;
}

/**
 * Implements hook_menu().
 */
function cu_seo_bundle_menu() {
  $items = array();

  $items['admin/settings/seo'] = array(
    'title' => 'Search Engine Optimization',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer express settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'weight' => 6,
  );

  $items['admin/settings/seo/xmlsitemap'] = array(
    'title' => 'Sitemap',
    'description' => 'Configure sitemap settings.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/config/search/xmlsitemap'),
    'access arguments' => array('administer express settings'),
    'weight' => 26,
  );

  return $items;
}

function cu_seo_bundle_page_alter(&$vars) {
  // hide advanced settings from non-developers.
  if ((current_path() == 'admin/config/search/xmlsitemap/settings') && (!in_array('developer', $user->roles) && $user->uid != 1)) {
    drupal_access_denied();
    drupal_exit();
  }
}
