<?php

/**
 * @file
 * Version.
 */


/**
 * Combines the version of core and profile.
 */
function express_version_get_version() {
  $profile_version = _express_version_determine_profile_version();
  $profile_version_parts = explode('-', $profile_version);

  $core_version = VERSION;
  $core_parts = explode('.', $core_version);

  return $profile_version_parts[1] . '.' . $core_parts[2];
}

/**
 * Determines the installed profile and its version.
 */
function _express_version_determine_profile_version() {
  require_once DRUPAL_ROOT . '/includes/install.inc';

  // Determine installation profile used.
  $profile = variable_get('install_profile', '');
  $parse = install_profile_info($profile);
  return $parse['version'];

}
