<?php

/**
 * @file
 * Contains hooks for lando_hosting module.
 */

/**
 * Implements hook_form_alter().
 *
 * Mirrors changes cu_ldap makes without the overhead of LDAP.
 */
function local_hosting_form_user_login_alter(&$form, &$form_state) {
  $form['name']['#title'] = t('CU Login Name');
  $form['name']['#description'] = '';
  $form['pass']['#title'] = t('IdentiKey Password');
  $form['pass']['#description'] = '';
}

/**
 * Implements hook_url_outbound_alter().
 *
 * Fix Drupal autocomplete on environments with restricted access to PHP files.
 * @see https://github.com/CuBoulder/express-starter/issues/27 .
 */
function local_hosting_url_outbound_alter(&$path, &$options, $original_path) {
  if (isset($options['script']) && $options['script'] == 'index.php') {
    $options['script'] = '';
  }
}
