<?php

/**
 * Alters grouping in admin/modules for CU specific sites.
 * @file
 */

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function cu_profile_module_manager_menu() {

  $items['admin/settings/bundles/list/available'] = array(
    'title' => 'Available',
    'type' => MENU_LOCAL_TASK,
    'description' => 'Add and request additional bundles',
    'page callback' => 'cu_profile_module_manager_bundles',
    'file' => 'cu_profile_module_manager.admin.inc',
    'page arguments' => array(FALSE, NULL, NULL),
    'access arguments' => array('enable module bundles'),
    'weight' => 10,
  );

  return $items;
}

/**
 * Implementes hook_menu_alter().
 */
function cu_profile_module_manager_menu_alter(&$items) {
  $items['admin/settings/bundles/list']['page callback'] = 'cu_profile_module_manager_bundles';
  $items['admin/settings/bundles/list']['page arguments'] = array(TRUE, NULL, NULL);
  $items['admin/settings/bundles/list']['module'] = 'cu_profile_module_manager';
  $items['admin/settings/bundles/list']['file'] = 'cu_profile_module_manager.admin.inc';
  $items['admin/settings/bundles/list']['title'] = 'Bundles';
  $items['admin/settings/bundles/list/core']['title'] = 'Installed';
}

/**
 * Implementes hook_theme().
 */
function cu_profile_module_manager_theme() {
  $registry = array();
  $template_dir = drupal_get_path('module', 'cu_profile_module_manager') . '/templates';
  $registry['express_bundle'] = array(
    'template' => 'express-bundle',
    'path' => $template_dir,
    'render element' => 'elements',
  );
  return $registry;
}

/**
 * Implements hook_secure_permissions.
 */
function cu_profile_module_manager_secure_permissions($role) {
  $permissions = array(
    'site_owner' => array(
      'enable module bundles',
    ),
    'configuration_manager' => array(
      'enable module bundles',
    ),
    'administrator' => array(
      'enable module bundles',
      'skip bundle request step',
    ),
    'developer' => array(
      'enable module bundles',
      'skip bundle request step',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
